### ISSUE TITLE
Beat won't detect any files

### ISSUE THREAD

**Issue by rmarji** [GoogleCloudPlatform/gcsbeat#11]
I have tried local file approach and adding the bucket name. and it keeps saying files pending 0

it doesn't detect the files I wanted to be processed although I tried everything as a pattern from "*" to writing the file name exactly.

the file name is app.json and I have it in GCS in a bucket in a subfolder called android. what I'm doing wrong?

**Comment by josephlewis42** [comment]
Hi @rmarji would you mind including your beat configuration `.yml` file and any flags you're using to execute gcsbeat?

One thing that might be going on is `gcsbeat` will keep a database of already processed files and won't re-upload them so that database might be hanging around on your system.

Cheers!

**Comment by rmarji** [comment]
```
gcsbeat:
  interval: 1000s
  bucket_id: file:///home/<folder>/ or <bucket_name>
  json_key_file: key-test.json
  delete: false
  file_matches: "app.json"
  #file_exclude: "bak_*"
  #metadata_key: x-goog-meta-gcsbeat
  codec: "json-array"
  unpack_gzip: false
  processed_db_path: "processed_file_list.db"

```

that crossed my mind, and I deleted the db multiple times with the same result. I have never got any files download.
I replaced the values for the folder and bucketname. is there a format for the bucket name or jjust the name shown.
No Flags are used. it doesn't work on either the file system nor the bucket. and if I put a made up bucket name. it doesn't verify if that bucket actually exists so it was a bit confusing to check if I'm doing things correctly

**Comment by josephlewis42** [comment]
The bucket name should be whatever you set it up to be in your GCP project.

Whoops, I missed that you were using a sub-folder in the original comment, I'm wondering if you'll have success if you move `app.json` into the root of your bucket and set the file_matches to `*.json` or maybe use `android/*.json` instead.

I also noticed you're using the `json-array` type rather than `json-stream`, make sure that's the one you want. If the objects are in an array in the file `[{"foo":33},{"foo":44}]` you'll want the array, but if they're top level without separators e.g. `{"foo":33}{"foo":44}` you'll want `json-stream`.

Cheers!

**Comment by rmarji** [comment]
I have tried all of the above including rebuilding the beat from the source code.

it's really confusing why this is happening. is there a way to debug if the beat is actually reading the files correctly maybe it is excluding my files somehow. but I have no way of finding out.

**Comment by rmarji** [comment]
BTW thanks for your responses. I hope we can resolve this. I'm using Ubuntu with Python 3.6 (if that changes anything) and do you know of any different approach to import files that exist on GCS?

**Comment by rmarji** [comment]
@josephlewis42 any idea why this is not working? is there more info I can share with you?

**Comment by josephlewis42** [comment]
Hi @rmarji, I've been able to start digging into this a little last night and this morning. Right now I don't have a way to dump why file X was excluded vs included, but I think that would be a great addition, I'm adding a bug #15 to track that; feel free to add any comments there if there's something in particular you'd like to see.

I found one bug #14	which is causing some phantom files to appear due to the way GCS handles directories.

I also started working on a [tutorial](https://github.com/GoogleCloudPlatform/gcsbeat/blob/cloudshell-tutorial/tutorial/tutorial.md) that you'll be able to launch in CloudShell from the `README.md` file. Hopefully that'll provide a good jumping off point in the future.

For other options, there's ~~logstash-input-google_cloud_storage~~ (edit: whoops, we have an output, not an input) if you wanted to use a Logstash plugin. You could also use [cloud functions](https://cloud.google.com/functions/docs/calling/storage) to insert data to your Elastic when files change in your bucket.

**Comment by josephlewis42** [comment]
I just released [v1.1.0 of the beat](https://github.com/GoogleCloudPlatform/gcsbeat/releases/tag/v1.1.0) which includes enhanced debugging showing you a step-by-step explanation of why files were included/excluded. Hopefully that'll help you debug this issue.

More details about how to use it and read the output are in the [main README file](https://github.com/GoogleCloudPlatform/gcsbeat#debug).

Cheers!

**Comment by rmarji** [comment]
thanks @josephlewis42 I managed to get it to work using your tutorial config. still not sure what was the main problem. once I do I will post back here. appreciate your work. was a life saver.
